feat: merge pull request api
Mohaymen-ICT/Mohaymen.GiteaClient pull request #21
Opened 2024-07-31 13:26 UTC by HamedSY

2024-08-03 04:35 UTC, MKasaei00 requested changes
خسته نباشی حامد جان
یه سری موارد رو دیدم کامنت گذاشتم

2024-08-03 04:35 UTC, MKasaei00 commented on Mohaymen.GiteaClient/Gitea/PullRequest/Common/Enums/Extensions/EnumExtensions.cs
> +    public static string Normalize<T>(this T enumValue) where T : Enum
منطق تابع مقادیر PascalCase رو به kebab-case تبدیل می‌کنه درسته؟
چرا به این نیاز داریم؟

2024-08-03 04:35 UTC, MKasaei00 commented on Mohaymen.GiteaClient/Gitea/PullRequest/Common/Enums/SortCriteria.cs
> +    Recentupdate,
چرا اینا رو تغییر نام دادیم؟

2024-08-03 04:35 UTC, MKasaei00 commented on Mohaymen.GiteaClient/Gitea/PullRequest/Common/Enums/Extensions/EnumExtensions.cs
> +    public static string Normalize<T>(this T enumValue) where T : Enum
اگر فرض بالا درسته یه سامری برای تابع بنویسیم و این رو بگیم که خواننده‌ی کد سریع‌تر متوجه بشه

2024-08-03 04:35 UTC, MKasaei00 commented on Mohaymen.GiteaClient/Gitea/PullRequest/MergePullRequest/Commands/MergePullRequestCommand.cs
> +    public bool DeleteBranchAfterMerge { get; init; }
اینا بهتر نیست مقدار پیشفرض داشته باشن؟

2024-08-03 04:35 UTC, MKasaei00 commented on Mohaymen.GiteaClient/Gitea/PullRequest/MergePullRequest/Commands/MergePullRequestCommand.cs
> +    public bool ForceMerge { get; init; }
اینا بهتر نیست مقدار پیشفرض داشته باشن؟

2024-08-03 04:35 UTC, MKasaei00 commented on Mohaymen.GiteaClient/Gitea/PullRequest/MergePullRequest/Commands/MergePullRequestCommand.cs
> +    public bool MergeWhenChecksSucceed { get; init; }
اینا بهتر نیست مقدار پیشفرض داشته باشن؟

2024-08-03 04:35 UTC, MKasaei00 commented on Mohaymen.GiteaClient/Gitea/PullRequest/MergePullRequest/Commands/MergePullRequestCommand.cs
> +    public string? MergeTitle { get; init; }
چرا اختیاری هستند؟

2024-08-03 04:35 UTC, MKasaei00 commented on Mohaymen.GiteaClient/Gitea/PullRequest/MergePullRequest/Commands/MergePullRequestCommand.cs
> +    public string? MergeMessage { get; init; }
چرا اختیاری هستند؟

2024-08-03 04:35 UTC, MKasaei00 commented on Mohaymen.GiteaClient/Gitea/PullRequest/MergePullRequest/Validators/MergePullRequestCommandValidator.cs
> +        RuleFor(x => x.Index)
empty line before this

2024-08-03 04:35 UTC, MKasaei00 commented on Mohaymen.GiteaClient/Gitea/PullRequest/MergePullRequest/Validators/MergePullRequestCommandValidator.cs
> +        RuleFor(x => x.Index)
منظور از Index
همون Id هست؟
اگر بله یه کامنتی چیزی توی کلاس اصلی بذاریم

2024-08-03 04:35 UTC, MKasaei00 commented on Mohaymen.GiteaClient.Tests/Gitea/PullRequest/Common/Enums/Extensions/EnumExtensionsTests.cs
> +        // Act
عبارت 
Arrange 
رو بذاریم ولی خالی باشه بهتره به نظرم

2024-08-03 04:35 UTC, MKasaei00 commented on Mohaymen.GiteaClient.Tests/Gitea/PullRequest/GetPullRequestList/Commands/GetPullRequestListCommandHandlerTests.cs
> +            State = EnumExtensions.Normalize(pullRequestState),
چرا این تغییر کرده؟

2024-08-03 04:35 UTC, MKasaei00 commented on Mohaymen.GiteaClient.IntegrationTests/Gitea/PullRequest/MergePullRequest/MergePullRequestTests.cs
> +        getPullRequestListResponse.Content!.First().Merged.Should().BeTrue();
getPullRequestListResponse.Content
اندازه‌ی این لیست assert نشده

2024-08-04 12:44 UTC, HamedSY commented on Mohaymen.GiteaClient/Gitea/PullRequest/Common/Enums/Extensions/EnumExtensions.cs
> +    public static string Normalize<T>(this T enumValue) where T : Enum
اره درسته، تست هم براش نوشتم
برای اینکه اون string هایی که باید تو اون فیلد api بذاریم ساخته بشن. پارامتر api که نمی‌تونه enum باشه، و خب toString هم کفایت نمی‌کنه

2024-08-04 12:46 UTC, HamedSY commented on Mohaymen.GiteaClient/Gitea/PullRequest/Common/Enums/SortCriteria.cs
> +    Recentupdate,
دیدم که اون string های ولید برای پارامتر api دیگه dash نداره برای این موارد و خب اگه مثل قبل می‌موند تابع Normalize ما اشتباه normalize می‌کرد. اینم تصویر این پارامتر api:
![image](https://github.com/user-attachments/assets/78c9e478-fe33-45ce-9c6b-7d2edf9cff16)

2024-08-04 12:50 UTC, HamedSY commented on Mohaymen.GiteaClient/Gitea/PullRequest/Common/Enums/Extensions/EnumExtensions.cs
> +    public static string Normalize<T>(this T enumValue) where T : Enum
Done

2024-08-04 12:53 UTC, HamedSY commented on Mohaymen.GiteaClient/Gitea/PullRequest/MergePullRequest/Commands/MergePullRequestCommand.cs
> +    public bool DeleteBranchAfterMerge { get; init; }
مقدار دیفالت bool که کلا false عه
باقیش هم یا required هستن یا nullable

2024-08-04 12:54 UTC, HamedSY commented on Mohaymen.GiteaClient/Gitea/PullRequest/MergePullRequest/Commands/MergePullRequestCommand.cs
> +    public bool ForceMerge { get; init; }
بالا گفتم

2024-08-04 12:54 UTC, HamedSY commented on Mohaymen.GiteaClient/Gitea/PullRequest/MergePullRequest/Commands/MergePullRequestCommand.cs
> +    public bool MergeWhenChecksSucceed { get; init; }
بالا گفتم

2024-08-04 12:55 UTC, HamedSY commented on Mohaymen.GiteaClient/Gitea/PullRequest/MergePullRequest/Commands/MergePullRequestCommand.cs
> +    public string? MergeMessage { get; init; }
بالا گفتم

2024-08-04 12:58 UTC, HamedSY commented on Mohaymen.GiteaClient/Gitea/PullRequest/MergePullRequest/Validators/MergePullRequestCommandValidator.cs
> +        RuleFor(x => x.Index)
اینه پارامترش. آیدی نمی‌دونم میشه گفت، همون index عه

![image](https://github.com/user-attachments/assets/e37c711b-db14-4291-8b7f-9e8d1de470cd)

2024-08-04 12:59 UTC, HamedSY commented on Mohaymen.GiteaClient/Gitea/PullRequest/MergePullRequest/Validators/MergePullRequestCommandValidator.cs
> +        RuleFor(x => x.Index)
مثل همین pr که داری می‌بینی که indexش ۲۱ عه

![image](https://github.com/user-attachments/assets/8ac5cc89-e0c5-47ee-877b-2ceb82ffada7)

2024-08-04 13:00 UTC, HamedSY commented on Mohaymen.GiteaClient.Tests/Gitea/PullRequest/Common/Enums/Extensions/EnumExtensionsTests.cs
> +        // Act
Done

2024-08-04 13:06 UTC, HamedSY commented on Mohaymen.GiteaClient.Tests/Gitea/PullRequest/GetPullRequestList/Commands/GetPullRequestListCommandHandlerTests.cs
> +            State = EnumExtensions.Normalize(pullRequestState),
اشتباه شد برش گردوندم

2024-08-04 13:08 UTC, HamedSY commented on Mohaymen.GiteaClient.IntegrationTests/Gitea/PullRequest/MergePullRequest/MergePullRequestTests.cs
> +        getPullRequestListResponse.Content!.First().Merged.Should().BeTrue();
متوجه کامنت نشدم

2024-08-04 13:45 UTC, MKasaei00 commented on Mohaymen.GiteaClient.IntegrationTests/Gitea/PullRequest/MergePullRequest/MergePullRequestTests.cs
> +        getPullRequestListResponse.Content!.First().Merged.Should().BeTrue();
getPullRequestListResponse.Content
این لیست ممکنه بیش از یک آیتم داشته باشه

2024-08-04 13:46 UTC, MKasaei00 commented on Mohaymen.GiteaClient.IntegrationTests/Gitea/PullRequest/MergePullRequest/MergePullRequestTests.cs
> +        getPullRequestListResponse.Content!.First().Merged.Should().BeTrue();
خیلی مهم نیست البته

2024-08-05 07:39 UTC, HamedSY commented on Mohaymen.GiteaClient.IntegrationTests/Gitea/PullRequest/MergePullRequest/MergePullRequestTests.cs
> +        getPullRequestListResponse.Content!.First().Merged.Should().BeTrue();
درست کردم

2024-08-05 08:13 UTC, MKasaei00 approved these changes

2024-08-05 08:14 UTC, merged