Feature/add create branch api
Mohaymen-ICT/Mohaymen.GiteaClient pull request #3
Opened 2024-07-14 13:42 UTC by HamedSY

creating branch in gitea

2024-07-17 06:36 UTC, mostmand requested changes

2024-07-17 06:36 UTC, mostmand commented on Mohaymen.GiteaClient/Gitea/Branch/CreateBranch/Commands/CreateBranchCommand.cs
> +    public string RepositoryName { get; init; }
وارنینگ‌هایی که گیت‌هاب روی کد گذاشته رو رفع کن

2024-07-17 06:36 UTC, mostmand commented on Mohaymen.GiteaClient/Gitea/Branch/CreateBranch/Commands/CreateBranchCommand.cs
> +    public string RepositoryName { get; init; }
این فایل و سایر فایل‌ها از این وارنینگ‌ها داره

2024-07-17 06:36 UTC, mostmand commented on Mohaymen.GiteaClient/Gitea/Branch/CreateBranch/Mappers/CreateBranchCommandMapper.cs
> +using Riok.Mapperly.Abstractions;
چه نیازی به mapperly هست؟ چرا دستی اینا رو مپ نکردین؟

2024-07-17 13:15 UTC, HamedSY commented on Mohaymen.GiteaClient/Gitea/Branch/CreateBranch/Commands/CreateBranchCommand.cs
> +    public string RepositoryName { get; init; }
Done

2024-07-18 07:57 UTC, HamedSY commented on Mohaymen.GiteaClient/Gitea/Branch/CreateBranch/Mappers/CreateBranchCommandMapper.cs
> +using Riok.Mapperly.Abstractions;
به مپ دستی تغییرش دادم

2024-07-18 08:12 UTC, mostmand approved these changes

2024-07-18 08:15 UTC, merged